/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package abd.p1.view;

import abd.p1.controller.EditarPerfilController;
import abd.p1.model.Usuario;

/**
 *
 * @author Rodrigo y David
 */

@SuppressWarnings({ "serial", "unused" })
public class EditarPerfilDialog extends javax.swing.JDialog {
	
	private EditarPerfilController controller;
    private String contrasenia;
	private Usuario usuario;
    private boolean editable = true;
    private int distancia = -1;
    private double latitudOrigen;
    private double longitudOrigen;
	
    /**
     * Creates new form EditarPerfilDialog
     */
    public EditarPerfilDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public EditarPerfilDialog(EditarPerfilController controller) {
		this(null, true);
		this.controller = controller;
		perfilPanel1.setController(this.controller);
	}
    
    public EditarPerfilDialog(EditarPerfilController controller, Usuario usuario, boolean editable, double latO, double lonO) {
		this(null, true);
		this.controller = controller;
		perfilPanel1.setController(this.controller);
	
		this.usuario = usuario;
		perfilPanel1.rellenarVentana(usuario, editable);
		setEditable(editable);
		if (!editable) {
			setLatitudOrigen(latO);
			setLongitudOrigen(lonO);
			controller.determinarDistancia(this);
		}
	}

	// Getters and setters
    public String getContrasenia() {
		return contrasenia;
	}

	public void setContrasenia(String contrasenia) {
		this.contrasenia = contrasenia;
	}
	
	public void setDistancia(int distancia) {
		this.distancia = distancia;
		if (this.distancia != -1) {
			labelDistancia.setText("Distancia: " + distancia + "m");
		} else {
			labelDistancia.setText("Distancia: no expecificada");
		}
	}

	public double getLatitudOrigen() {
		return latitudOrigen;
	}

	public void setLatitudOrigen(double latitudOrigen) {
		this.latitudOrigen = latitudOrigen;
	}

	public double getLongitudOrigen() {
		return longitudOrigen;
	}

	public void setLongitudOrigen(double longitudOrigen) {
		this.longitudOrigen = longitudOrigen;
	}

	public boolean isEditable() {
		return editable;
	}

	public void setEditable(boolean editable) {
		this.editable = editable;
		buttonCambiarContrasenia.setVisible(editable);
		buttonCancelar.setVisible(editable);
		buttonGuardarCambios.setVisible(editable);
		labelDistancia.setVisible(!editable);
	}

	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        perfilPanel1 = new abd.p1.view.PerfilPanel();
        buttonCambiarContrasenia = new javax.swing.JButton();
        buttonCancelar = new javax.swing.JButton();
        buttonGuardarCambios = new javax.swing.JButton();
        labelDistancia = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        perfilPanel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                perfilPanel1FocusLost(evt);
            }
        });

        buttonCambiarContrasenia.setText("Cambiar contraseña");
        buttonCambiarContrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCambiarContraseniaActionPerformed(evt);
            }
        });

        buttonCancelar.setText("Cancelar");
        buttonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarActionPerformed(evt);
            }
        });

        buttonGuardarCambios.setText("Guardar cambios");
        buttonGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGuardarCambiosActionPerformed(evt);
            }
        });

        labelDistancia.setText("Distancia: no expecificada");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(perfilPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonCambiarContrasenia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonGuardarCambios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelDistancia)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(perfilPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDistancia)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCambiarContrasenia)
                    .addComponent(buttonCancelar)
                    .addComponent(buttonGuardarCambios))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCambiarContraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCambiarContraseniaActionPerformed
        controller.cambiarContrasenia(this);
    }//GEN-LAST:event_buttonCambiarContraseniaActionPerformed

    private void buttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarActionPerformed
        controller.cancelar(this);
    }//GEN-LAST:event_buttonCancelarActionPerformed

    private void buttonGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGuardarCambiosActionPerformed
        controller.guardarCambios(this);
    }//GEN-LAST:event_buttonGuardarCambiosActionPerformed

    private void perfilPanel1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_perfilPanel1FocusLost
     
    }//GEN-LAST:event_perfilPanel1FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarPerfilDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarPerfilDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarPerfilDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarPerfilDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditarPerfilDialog dialog = new EditarPerfilDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCambiarContrasenia;
    private javax.swing.JButton buttonCancelar;
    private javax.swing.JButton buttonGuardarCambios;
    private javax.swing.JLabel labelDistancia;
    private abd.p1.view.PerfilPanel perfilPanel1;
    // End of variables declaration//GEN-END:variables

}
