/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package abd.p1.view;

import javax.swing.DefaultListModel;

import abd.p1.controller.ListPreguntaController;
import abd.p1.model.Pregunta;

/**
 *
 * @author Rodrigo y David
 */
@SuppressWarnings("serial")
public class ListPreguntaPanel extends javax.swing.JPanel {

	private ListPreguntaController controller;
	
    /**
     * Creates new form ListPreguntaPanel
     */
    public ListPreguntaPanel() {
        initComponents();
//        Pregunta p1 = new Pregunta(1, "Pregunta 1");
//        Pregunta p2 = new Pregunta(2, "Pregunta 2");
//        p2.getOpciones().add(new Opcion());
//        p2.getOpciones().add(new Opcion());
//        Pregunta p3 = new Pregunta(3, "Pregunta 3");
//        p3.getOpciones().add(new Opcion());
//        p3.getOpciones().add(new Opcion());
//        p3.getOpciones().add(new Opcion());
//        p3.getOpciones().add(new Opcion());
//        DefaultListModel<Pregunta> modelo = new DefaultListModel<>();
//        modelo.addElement(p1);
//        modelo.addElement(p2);
//        modelo.addElement(p3);
//        listaPreguntas.setModel(modelo);
//        listaPreguntas.setCellRenderer(new PreguntaCellRenderer());
    }
    
    public void setController(ListPreguntaController controller) {
    	this.controller = controller;
    }

    public void setModel(DefaultListModel<Pregunta> modelo) {
    	listaPreguntas.setModel(modelo);
    }

    public void setCellRenderer(PreguntaCellRenderer pcr) {
    	listaPreguntas.setCellRenderer(pcr);
    }
    
    public void inicializarListaPreguntas() {
    	controller.obtenerListaPreguntas(this);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaPreguntas = new javax.swing.JList<>();
        buttonResponder = new javax.swing.JButton();
        buttonPreguntaAleatoria = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jScrollPane1.setViewportView(listaPreguntas);

        buttonResponder.setText("Responder");
        buttonResponder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResponderActionPerformed(evt);
            }
        });

        buttonPreguntaAleatoria.setText("Pregunta aleatoria");
        buttonPreguntaAleatoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPreguntaAleatoriaActionPerformed(evt);
            }
        });

        jLabel1.setText("Mejor valoradas:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(buttonResponder)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonPreguntaAleatoria)))
                        .addGap(0, 96, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonResponder)
                    .addComponent(buttonPreguntaAleatoria))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonResponderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResponderActionPerformed
        if (!listaPreguntas.isSelectionEmpty()) {
        	Pregunta pregunta = listaPreguntas.getSelectedValue();
        	controller.ResponderPregunta(this, pregunta);
        }
    }//GEN-LAST:event_buttonResponderActionPerformed

    private void buttonPreguntaAleatoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPreguntaAleatoriaActionPerformed
    	if (listaPreguntas.getModel().getSize() > 0) {
    		controller.ResponderPreguntaAleatoria(this);
    	}
    }//GEN-LAST:event_buttonPreguntaAleatoriaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonPreguntaAleatoria;
    private javax.swing.JButton buttonResponder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Pregunta> listaPreguntas;
    // End of variables declaration//GEN-END:variables
}
