/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package abd.p1.view;

import abd.p1.controller.ListUserController;
import abd.p1.model.Usuario;

import javax.swing.DefaultListModel;

/**
 *
 * @author Rodrigo y David
 */
@SuppressWarnings("serial")
public class ListUserPanel extends javax.swing.JPanel {

	private ListUserController controller;

	/**
     * Creates new form ListUserPanel
     */
    public ListUserPanel() {
    	initComponents();
    }
    
    public void setController(ListUserController controller) {
    	this.controller = controller;
    }
    
    public void setModel(DefaultListModel<Usuario> modelo) {
    	listaUsuarios.setModel(modelo);
    }

    public void setCellRenderer(UsuarioCellRenderer ucr) {
    	listaUsuarios.setCellRenderer(ucr);
    }
    
    public void inicializarListaUsuarios() {
    	controller.obtenerListaUsuariosPorUbicacion(this, "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaUsuarios = new javax.swing.JList<>();
        checkBoxFiltrar = new javax.swing.JCheckBox();
        jTextField1 = new javax.swing.JTextField();
        checkBoxAmigos = new javax.swing.JCheckBox();
        buttonModificarPerfil = new javax.swing.JButton();
        buttonVerPerfil = new javax.swing.JButton();

        jScrollPane1.setViewportView(listaUsuarios);

        checkBoxFiltrar.setText("Filtrar por nombre:");
        checkBoxFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxFiltrarActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        checkBoxAmigos.setText("Mostrar sólo amigos");

        buttonModificarPerfil.setText("Modificar mi perfil");
        buttonModificarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModificarPerfilActionPerformed(evt);
            }
        });

        buttonVerPerfil.setText("Ver perfil seleccionado");
        buttonVerPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVerPerfilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(buttonModificarPerfil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonVerPerfil)
                .addContainerGap(79, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkBoxFiltrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkBoxAmigos)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBoxFiltrar)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkBoxAmigos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonModificarPerfil)
                    .addComponent(buttonVerPerfil))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        if (checkBoxFiltrar.isSelected()) {
        	String cadena = "";
        	if (!jTextField1.getText().isEmpty()) {
        		cadena = jTextField1.getText();
        	}
        	controller.obtenerListaUsuarios(this, cadena);
        }
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void buttonModificarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModificarPerfilActionPerformed
        controller.modificarPerfil();
    }//GEN-LAST:event_buttonModificarPerfilActionPerformed

    private void buttonVerPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVerPerfilActionPerformed
        Usuario usuarioSeleccionado = listaUsuarios.getSelectedValue();
        controller.verPerfil(usuarioSeleccionado);
    }//GEN-LAST:event_buttonVerPerfilActionPerformed

    private void checkBoxFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxFiltrarActionPerformed
    	String cadena = "";
    	if (!jTextField1.getText().isEmpty()) {
    		cadena = jTextField1.getText();
    	}
    	if (checkBoxFiltrar.isSelected()) {
    		controller.obtenerListaUsuariosPorUbicacion(this, cadena);
    	} else {
    		controller.obtenerListaUsuariosPorUbicacion(this, "");
    	}
    }//GEN-LAST:event_checkBoxFiltrarActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonModificarPerfil;
    private javax.swing.JButton buttonVerPerfil;
    private javax.swing.JCheckBox checkBoxAmigos;
    private javax.swing.JCheckBox checkBoxFiltrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JList<Usuario> listaUsuarios;
    // End of variables declaration//GEN-END:variables
}
