/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package abd.p1.view;

import java.util.ArrayList;
import java.util.List;

import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;

import abd.p1.controller.EditarPerfilController;
import abd.p1.model.Usuario;

/**
 *
 * @author Rodrigo y David
 */
@SuppressWarnings("serial")
public class PerfilPanel extends javax.swing.JPanel {

	private String sexo = "Masculino";
	private String preferencia = "Femenino";
	private boolean editable = true;
	private EditarPerfilController controller;
	
    /**
     * Creates new form PerfilPanel
     */
    public PerfilPanel() {
        initComponents();
    }
    
    // Getters and setters
    public String getSexo() {
		return sexo;
	}
    
    public void setSexo(String sexo) {
		this.sexo = sexo;
		labelSexo.setText("Sexo: " + sexo);
	}
    
    public String getPreferencia() {
		return preferencia;
	}

	public void setPreferencia(String preferencia) {
		this.preferencia = preferencia;
		labelBusca.setText("Busca: " + preferencia);
	}
	
	public boolean isEditable() {
        return editable;
    }
	
	public void setModel(DefaultListModel<String> aficionesModel) {
		listAficiones.setModel(aficionesModel);
	}

    public void setEditable(boolean editable) {
        this.editable = editable;
        buttonCambiarAvatar.setVisible(editable);
        textAreaDescripcion.setEditable(editable);
        buttonAniadirAficion.setVisible(editable);
        buttonEliminarAficion.setVisible(editable);
        buttonEditarSeleccionada.setVisible(editable);
        buttonCambiarSexo.setVisible(editable);
        buttonCambiarPreferencia.setVisible(editable);
    }

	public String getDescripcion() {
		return textAreaDescripcion.getText();
	}

	public void setDescripcion(String descripcion) {
		this.textAreaDescripcion.setText(descripcion);
	}

	public javax.swing.JList<String> getListAficiones() {
		return listAficiones;
	}

	public void setListAficiones(javax.swing.JList<String> listAficiones) {
		this.listAficiones = listAficiones;
	}

	public EditarPerfilController getController() {
		return controller;
	}

	public void setController(EditarPerfilController controller) {
		this.controller = controller;
		userPanel1.setController(controller);
	}
	
	public void setIcon(ImageIcon icon) {
		userPanel1.setIcon(icon);
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userPanel1 = new abd.p1.view.UserPanel();
        buttonCambiarAvatar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaDescripcion = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listAficiones = new javax.swing.JList<>();
        buttonAniadirAficion = new javax.swing.JButton();
        buttonEliminarAficion = new javax.swing.JButton();
        buttonEditarSeleccionada = new javax.swing.JButton();
        labelSexo = new javax.swing.JLabel();
        labelBusca = new javax.swing.JLabel();
        buttonCambiarSexo = new javax.swing.JButton();
        buttonCambiarPreferencia = new javax.swing.JButton();

        buttonCambiarAvatar.setText("Cambiar avatar");
        buttonCambiarAvatar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCambiarAvatarActionPerformed(evt);
            }
        });

        jLabel1.setText("Descripción:");

        textAreaDescripcion.setColumns(20);
        textAreaDescripcion.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        textAreaDescripcion.setRows(5);
        textAreaDescripcion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textAreaDescripcionFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(textAreaDescripcion);

        jLabel2.setText("Aficiones:");

        jScrollPane2.setViewportView(listAficiones);

        buttonAniadirAficion.setText("Añadir afición");
        buttonAniadirAficion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAniadirAficionActionPerformed(evt);
            }
        });

        buttonEliminarAficion.setText("Eliminar seleccionada");
        buttonEliminarAficion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEliminarAficionActionPerformed(evt);
            }
        });

        buttonEditarSeleccionada.setText("Editar seleccionada");
        buttonEditarSeleccionada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditarSeleccionadaActionPerformed(evt);
            }
        });

        labelSexo.setText("Sexo:");

        labelBusca.setText("Busca:");

        buttonCambiarSexo.setText("Cambiar sexo");
        buttonCambiarSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCambiarSexoActionPerformed(evt);
            }
        });

        buttonCambiarPreferencia.setText("Cambiar preferencia");
        buttonCambiarPreferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCambiarPreferenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonCambiarAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(buttonEliminarAficion, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                                    .addComponent(buttonAniadirAficion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(buttonEditarSeleccionada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelBusca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelSexo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonCambiarSexo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonCambiarPreferencia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(userPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(buttonCambiarAvatar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelSexo)
                            .addComponent(buttonCambiarSexo)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonAniadirAficion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonEliminarAficion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonEditarSeleccionada)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCambiarPreferencia)
                    .addComponent(labelBusca))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCambiarAvatarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCambiarAvatarActionPerformed
    	controller.cambiarAvatar(this);
    }//GEN-LAST:event_buttonCambiarAvatarActionPerformed

    private void buttonAniadirAficionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAniadirAficionActionPerformed
        controller.aniadirAficion(this);
    }//GEN-LAST:event_buttonAniadirAficionActionPerformed

    private void buttonEliminarAficionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEliminarAficionActionPerformed
    	int indexAficion;
    	/*if (!listAficiones.isSelectionEmpty()) {
    		indexAficion = listAficiones.getSelectedIndex();
    	} else {
    		indexAficion = -1;
    	}*/
    	indexAficion = listAficiones.getSelectedIndex();
    	controller.eliminarAficion(this, indexAficion);
    }//GEN-LAST:event_buttonEliminarAficionActionPerformed

    private void buttonEditarSeleccionadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditarSeleccionadaActionPerformed
    	int indexAficion;
    	if (!listAficiones.isSelectionEmpty()) {
    		indexAficion = listAficiones.getSelectedIndex();
    	} else {
    		indexAficion = -1;
    	}
    	controller.editarAficion(this, indexAficion);
    }//GEN-LAST:event_buttonEditarSeleccionadaActionPerformed

    private void buttonCambiarSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCambiarSexoActionPerformed
        controller.cambiarSexo(this);
    }//GEN-LAST:event_buttonCambiarSexoActionPerformed

    private void buttonCambiarPreferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCambiarPreferenciaActionPerformed
        controller.cambiarPreferencia(this);
    }//GEN-LAST:event_buttonCambiarPreferenciaActionPerformed

    private void textAreaDescripcionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textAreaDescripcionFocusLost
        controller.obtenerDescipcion(this);
    }//GEN-LAST:event_textAreaDescripcionFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAniadirAficion;
    private javax.swing.JButton buttonCambiarAvatar;
    private javax.swing.JButton buttonCambiarPreferencia;
    private javax.swing.JButton buttonCambiarSexo;
    private javax.swing.JButton buttonEditarSeleccionada;
    private javax.swing.JButton buttonEliminarAficion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelBusca;
    private javax.swing.JLabel labelSexo;
    private javax.swing.JList<String> listAficiones;
    private javax.swing.JTextArea textAreaDescripcion;
    private abd.p1.view.UserPanel userPanel1;
    // End of variables declaration//GEN-END:variables

    @SuppressWarnings({ "rawtypes", "unchecked" })
	public void rellenarVentana(Usuario usuario, boolean editable) {
		setDescripcion(usuario.getDescripcion());
		DefaultListModel<String> aficionesModel = new DefaultListModel();
		List<String> aficiones = new ArrayList();
		System.out.println(usuario.getNombre());
		aficiones = usuario.getAficiones();
		System.out.println(aficiones);
		for (String a : aficiones) {
			aficionesModel.addElement(a);
		}
		setModel(aficionesModel);
		controller.setModel(aficionesModel);
		setSexo(usuario.getGenero().toString());
		setPreferencia(usuario.getInteres().toString());
		setEditable(editable);
		userPanel1.rellenarVentana(usuario, editable);
	}
    
}
