CREATE TABLESPACE GII_EMPRESA_MATANOTARIO DATAFILE 
'D:\oracle\GII_EMPRESA_MATANOTARIO' SIZE 5M AUTOEXTEND OFF;

-- Respuesta: tablespace GII_EMPRESA_PRUEBA creado.

CREATE USER USU_GII_MATANOTARIO IDENTIFIED BY USU_GII_MATANOTARIO DEFAULT
TABLESPACE GII_EMPRESA_MATANOTARIO TEMPORARY TABLESPACE TEMP QUOTA
UNLIMITED ON GII_EMPRESA_MATANOTARIO;

-- Respuesta: user USU_GII_MATANOTARIO creado.

GRANT CREATE SESSION, CREATE TABLE, DELETE ANY TABLE, SELECT ANY
DICTIONARY, CREATE ANY SEQUENCE TO USU_GII_MATANOTARIO;

-- Respuesta: GRANT correcto.